<a href="https://colab.research.google.com/github/CeskKim/AI-Study/blob/main/model/prophet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prophet quick start
import pandas as pd
from prophet import Prophet

# source data
df = pd.read_csv('https://raw.githubusercontent.com/facebook/prophet/main/examples/example_wp_log_peyton_manning.csv')
df.head()

# fit setting
m = Prophet()
m.fit(df)

future = m.make_future_dataframe(periods=365)
future.tail()

INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpaqlgr2hx/g25fkx5r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpaqlgr2hx/jqkxgxem.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.8/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25112', 'data', 'file=/tmp/tmpaqlgr2hx/g25fkx5r.json', 'init=/tmp/tmpaqlgr2hx/jqkxgxem.json', 'output', 'file=/tmp/tmpaqlgr2hx/prophet_modelbj_khq10/prophet_model-20230218121851.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
12:18:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
12:18:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

             ds
3265 2017-01-15
3266 2017-01-16
3267 2017-01-17
3268 2017-01-18
3269 2017-01-19

In [ ]:
# stock python package
!pip install finance-datareader
import FinanceDataReader as fdr

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting finance-datareader
  Downloading finance_datareader-0.9.50-py3-none-any.whl (19 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.8/dist-packages (from finance-datareader) (4.9.2)
Collecting requests-file
  Downloading requests_file-1.5.1-py2.py3-none-any.whl (3.7 kB)
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python3.8/dist-packages (from finance-datareader) (2.25.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from finance-datareader) (4.64.1)
Requirement already satisfied: pandas>=0.19.2 in /usr/local/lib/python3.8/dist-packages (from finance-datareader) (1.3.5)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.19.2->finance-datareader) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.19.2->finance-datareader) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.19.2->finance-datareader) (2022.7.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.3.0->finance-datareader) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.3.0->finance-datareader) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.3.0->finance-datareader) (2022.12.7)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.3.0->finance-datareader) (4.0.0)
Requirement already satisfied: six in /usr/local/lib/python3.8/dist-packages (from requests-file->finance-datareader) (1.15.0)
Installing collected packages: requests-file, finance-datareader
Successfully installed finance-datareader-0.9.50 requests-file-1.5.1

In [ ]:
# btc stock
bitcoin_stock = fdr.DataReader('BTC/KRW', '2022-12-01', '2023-02-18')
bitcoin_stock.tail()

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-02-14,27760044.0,28240970.0,27563498.0,28278196.0,28278196.0,3.409626e+13
2023-02-15,28277916.0,31213578.0,28250184.0,31213578.0,31213578.0,4.171166e+13
2023-02-16,NaN,NaN,NaN,NaN,NaN,NaN
2023-02-17,NaN,NaN,NaN,NaN,NaN,NaN
2023-02-18,31818654.0,32043548.0,31712138.0,31856266.0,31856266.0,4.675171e+13

In [ ]:
# prophet model
from prophet import Prophet
bitcoin_stock = fdr.DataReader('BTC/KRW', '2022-12-01', '2023-02-18')
bitcoin_stock.tail()
bitcoin_stock['y'] = bitcoin_stock['Close']
bitcoin_stock['ds'] = bitcoin_stock.index

pr = Prophet()
pr.fit(bitcoin_stock)

# prophet prediction period
future = pr.make_future_dataframe(periods=60)
forecast = pr.predict(future)
forecast.tail()
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].iloc[-40:-20]

INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmp2bdaykko/lclvjj46.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp2bdaykko/130qn_05.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.8/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62139', 'data', 'file=/tmp/tmp2bdaykko/lclvjj46.json', 'init=/tmp/tmp2bdaykko/130qn_05.json', 'output', 'file=/tmp/tmp2bdaykko/prophet_modelwvgcq432/prophet_model-20230218122001.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
12:20:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
12:20:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

            ds          yhat    yhat_lower    yhat_upper
100 2023-03-11  3.088291e+07  2.921725e+07  3.260146e+07
101 2023-03-12  3.070708e+07  2.889711e+07  3.254575e+07
102 2023-03-13  3.061909e+07  2.878031e+07  3.260359e+07
103 2023-03-14  3.079078e+07  2.883512e+07  3.286854e+07
104 2023-03-15  3.108055e+07  2.894302e+07  3.317722e+07
105 2023-03-16  3.085854e+07  2.871666e+07  3.313035e+07
106 2023-03-17  3.098191e+07  2.877970e+07  3.317515e+07
107 2023-03-18  3.128460e+07  2.885794e+07  3.372662e+07
108 2023-03-19  3.110878e+07  2.866128e+07  3.374796e+07
109 2023-03-20  3.102078e+07  2.836954e+07  3.366401e+07
110 2023-03-21  3.119247e+07  2.856134e+07  3.410649e+07
111 2023-03-22  3.148224e+07  2.855058e+07  3.450481e+07
112 2023-03-23  3.126023e+07  2.838214e+07  3.438095e+07
113 2023-03-24  3.138360e+07  2.823898e+07  3.456603e+07
114 2023-03-25  3.168630e+07  2.856169e+07  3.519964e+07
115 2023-03-26  3.151047e+07  2.810186e+07  3.490361e+07
116 2023-03-27  3.142248e+07  2.794554e+07  3.520772e+07
117 2023-03-28  3.159417e+07  2.801075e+07  3.556273e+07
118 2023-03-29  3.188394e+07  2.799759e+07  3.580308e+07
119 2023-03-30  3.166193e+07  2.746198e+07  3.587760e+07

In [ ]:
# btc 7주일 기준 측정